
name: Run Tests

on: 
  push:
    branches:   
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8' 
      - run: mvn test